// Banco de dados global unificado para o Nostalgia FC
// Banco de dados global unificado para o Nostalgia FC
const bancoJogadores = [
    // Juventus 93
    { name: "A. Peruzzi", posicao: "GOL", time: "Juventus", liga: "Série A", temporada: "93", rating: 83, cost: 80 },
    { name: "J. Kohler", posicao: "ZAG", time: "Juventus", liga: "Série A", temporada: "93", rating: 83, cost: 85 },
    { name: "M. Carrera", posicao: "ZAG", time: "Juventus", liga: "Série A", temporada: "93", rating: 78, cost: 65 },
    { name: "M. Torricelli", posicao: "ZAG", time: "Juventus", liga: "Série A", temporada: "93", rating: 80, cost: 70 },
    { name: "L. De Agostini", posicao: "ZAG", time: "Juventus", liga: "Série A", temporada: "93", rating: 79, cost: 65 },
    { name: "A. Conte", posicao: "MEI", time: "Juventus", liga: "Série A", temporada: "93", rating: 80, cost: 70 },
    { name: "A. Moeller", posicao: "MEI", time: "Juventus", liga: "Série A", temporada: "93", rating: 84, cost: 90 },
    { name: "G. Marocchi", posicao: "MEI", time: "Juventus", liga: "Série A", temporada: "93", rating: 78, cost: 60 },
    { name: "R. Baggio", posicao: "ATA", time: "Juventus", liga: "Série A", temporada: "93", rating: 90, cost: 140 },
    { name: "G. Vialli", posicao: "ATA", time: "Juventus", liga: "Série A", temporada: "93", rating: 85, cost: 95 },
    { name: "F. Ravanelli", posicao: "ATA", time: "Juventus", liga: "Série A", temporada: "93", rating: 83, cost: 85 },

    // Juventus 96
    { name: "A. Peruzzi", posicao: "GOL", time: "Juventus", liga: "Série A", temporada: "96", rating: 84, cost: 85 },
    { name: "C. Ferrara", posicao: "ZAG", time: "Juventus", liga: "Série A", temporada: "96", rating: 84, cost: 85 },
    { name: "P. Montero", posicao: "ZAG", time: "Juventus", liga: "Série A", temporada: "96", rating: 84, cost: 85 },
    { name: "G. Pessotto", posicao: "ZAG", time: "Juventus", liga: "Série A", temporada: "96", rating: 79, cost: 65 },
    { name: "M. Torricelli", posicao: "ZAG", time: "Juventus", liga: "Série A", temporada: "96", rating: 80, cost: 70 },
    { name: "D. Deschamps", posicao: "MEI", time: "Juventus", liga: "Série A", temporada: "96", rating: 85, cost: 95 },
    { name: "A. Conte", posicao: "MEI", time: "Juventus", liga: "Série A", temporada: "96", rating: 81, cost: 70 },
    { name: "A. Di Livio", posicao: "MEI", time: "Juventus", liga: "Série A", temporada: "96", rating: 81, cost: 70 },
    { name: "Z. Zidane", posicao: "MEI", time: "Juventus", liga: "Série A", temporada: "96", rating: 91, cost: 150 },
    { name: "A. Del Piero", posicao: "ATA", time: "Juventus", liga: "Série A", temporada: "96", rating: 88, cost: 120 },
    { name: "C. Vieri", posicao: "ATA", time: "Juventus", liga: "Série A", temporada: "96", rating: 86, cost: 105 },
    { name: "A. Boksic", posicao: "ATA", time: "Juventus", liga: "Série A", temporada: "96", rating: 83, cost: 85 },

    // Juventus 98
    { name: "A. Peruzzi", posicao: "GOL", time: "Juventus", liga: "Série A", temporada: "98", rating: 83, cost: 80 },
    { name: "P. Montero", posicao: "ZAG", time: "Juventus", liga: "Série A", temporada: "98", rating: 84, cost: 85 },
    { name: "C. Ferrara", posicao: "ZAG", time: "Juventus", liga: "Série A", temporada: "98", rating: 83, cost: 80 },
    { name: "M. Iuliano", posicao: "ZAG", time: "Juventus", liga: "Série A", temporada: "98", rating: 79, cost: 65 },
    { name: "G. Pessotto", posicao: "ZAG", time: "Juventus", liga: "Série A", temporada: "98", rating: 79, cost: 65 },
    { name: "E. Davids", posicao: "MEI", time: "Juventus", liga: "Série A", temporada: "98", rating: 85, cost: 95 },
    { name: "D. Deschamps", posicao: "MEI", time: "Juventus", liga: "Série A", temporada: "98", rating: 84, cost: 90 },
    { name: "Z. Zidane", posicao: "MEI", time: "Juventus", liga: "Série A", temporada: "98", rating: 91, cost: 150 },
    { name: "A. Di Livio", posicao: "MEI", time: "Juventus", liga: "Série A", temporada: "98", rating: 80, cost: 70 },
    { name: "A. Del Piero", posicao: "ATA", time: "Juventus", liga: "Série A", temporada: "98", rating: 88, cost: 120 },
    { name: "P. Inzaghi", posicao: "ATA", time: "Juventus", liga: "Série A", temporada: "98", rating: 83, cost: 85 },

    // Milan 90
    { name: "G. Galli", posicao: "GOL", time: "Milan", liga: "Série A", temporada: "90", rating: 81, cost: 75 },
    { name: "F. Baresi", posicao: "ZAG", time: "Milan", liga: "Série A", temporada: "90", rating: 87, cost: 110 },
    { name: "P. Maldini", posicao: "ZAG", time: "Milan", liga: "Série A", temporada: "90", rating: 89, cost: 130 },
    { name: "C. Costacurta", posicao: "ZAG", time: "Milan", liga: "Série A", temporada: "90", rating: 83, cost: 85 },
    { name: "M. Tassotti", posicao: "ZAG", time: "Milan", liga: "Série A", temporada: "90", rating: 82, cost: 75 },
    { name: "F. Rijkaard", posicao: "MEI", time: "Milan", liga: "Série A", temporada: "90", rating: 87, cost: 115 },
    { name: "C. Ancelotti", posicao: "MEI", time: "Milan", liga: "Série A", temporada: "90", rating: 82, cost: 75 },
    { name: "R. Donadoni", posicao: "MEI", time: "Milan", liga: "Série A", temporada: "90", rating: 84, cost: 90 },
    { name: "A. Evani", posicao: "MEI", time: "Milan", liga: "Série A", temporada: "90", rating: 80, cost: 70 },
    { name: "M. Van Basten", posicao: "ATA", time: "Milan", liga: "Série A", temporada: "90", rating: 91, cost: 150 },
    { name: "R. Gullit", posicao: "ATA", time: "Milan", liga: "Série A", temporada: "90", rating: 87, cost: 120 },

    // Milan 94
    { name: "S. Rossi", posicao: "GOL", time: "Milan", liga: "Série A", temporada: "94", rating: 82, cost: 80 },
    { name: "P. Maldini", posicao: "ZAG", time: "Milan", liga: "Série A", temporada: "94", rating: 89, cost: 130 },
    { name: "F. Baresi", posicao: "ZAG", time: "Milan", liga: "Série A", temporada: "94", rating: 87, cost: 110 },
    { name: "C. Costacurta", posicao: "ZAG", time: "Milan", liga: "Série A", temporada: "94", rating: 83, cost: 85 },
    { name: "M. Tassotti", posicao: "ZAG", time: "Milan", liga: "Série A", temporada: "94", rating: 81, cost: 75 },
    { name: "D. Albertini", posicao: "MEI", time: "Milan", liga: "Série A", temporada: "94", rating: 83, cost: 80 },
    { name: "M. Desailly", posicao: "MEI", time: "Milan", liga: "Série A", temporada: "94", rating: 84, cost: 90 },
    { name: "Z. Boban", posicao: "MEI", time: "Milan", liga: "Série A", temporada: "94", rating: 84, cost: 90 },
    { name: "R. Donadoni", posicao: "MEI", time: "Milan", liga: "Série A", temporada: "94", rating: 82, cost: 75 },
    { name: "D. Savicevic", posicao: "ATA", time: "Milan", liga: "Série A", temporada: "94", rating: 85, cost: 100 },
    { name: "D. Massaro", posicao: "ATA", time: "Milan", liga: "Série A", temporada: "94", rating: 81, cost: 75 },
    { name: "J. Papin", posicao: "ATA", time: "Milan", liga: "Série A", temporada: "94", rating: 83, cost: 85 },

    // Milan 99
    { name: "C. Abbiati", posicao: "GOL", time: "Milan", liga: "Série A", temporada: "99", rating: 80, cost: 70 },
    { name: "P. Maldini", posicao: "ZAG", time: "Milan", liga: "Série A", temporada: "99", rating: 88, cost: 125 },
    { name: "C. Costacurta", posicao: "ZAG", time: "Milan", liga: "Série A", temporada: "99", rating: 81, cost: 75 },
    { name: "T. Helveg", posicao: "ZAG", time: "Milan", liga: "Série A", temporada: "99", rating: 78, cost: 65 },
    { name: "R. Ayala", posicao: "ZAG", time: "Milan", liga: "Série A", temporada: "99", rating: 81, cost: 75 },
    { name: "D. Albertini", posicao: "MEI", time: "Milan", liga: "Série A", temporada: "99", rating: 82, cost: 75 },
    { name: "M. Ambrosini", posicao: "MEI", time: "Milan", liga: "Série A", temporada: "99", rating: 80, cost: 70 },
    { name: "Z. Boban", posicao: "MEI", time: "Milan", liga: "Série A", temporada: "99", rating: 83, cost: 85 },
    { name: "Leonardo", posicao: "MEI", time: "Milan", liga: "Série A", temporada: "99", rating: 83, cost: 85 },
    { name: "O. Bierhoff", posicao: "ATA", time: "Milan", liga: "Série A", temporada: "99", rating: 84, cost: 90 },
    { name: "G. Weah", posicao: "ATA", time: "Milan", liga: "Série A", temporada: "99", rating: 86, cost: 110 },

    // Inter 91
    { name: "W. Zenga", posicao: "GOL", time: "Inter", liga: "Série A", temporada: "91", rating: 85, cost: 90 },
    { name: "G. Bergomi", posicao: "ZAG", time: "Inter", liga: "Série A", temporada: "91", rating: 84, cost: 85 },
    { name: "R. Ferri", posicao: "ZAG", time: "Inter", liga: "Série A", temporada: "91", rating: 81, cost: 75 },
    { name: "A. Brehme", posicao: "ZAG", time: "Inter", liga: "Série A", temporada: "91", rating: 85, cost: 100 },
    { name: "G. Battistini", posicao: "ZAG", time: "Inter", liga: "Série A", temporada: "91", rating: 78, cost: 65 },
    { name: "L. Matthaus", posicao: "MEI", time: "Inter", liga: "Série A", temporada: "91", rating: 88, cost: 120 },
    { name: "N. Berti", posicao: "MEI", time: "Inter", liga: "Série A", temporada: "91", rating: 81, cost: 75 },
    { name: "M. Paganin", posicao: "MEI", time: "Inter", liga: "Série A", temporada: "91", rating: 77, cost: 60 },
    { name: "D. Bianchi", posicao: "MEI", time: "Inter", liga: "Série A", temporada: "91", rating: 77, cost: 60 },
    { name: "J. Klinsmann", posicao: "ATA", time: "Inter", liga: "Série A", temporada: "91", rating: 85, cost: 100 },
    { name: "A. Serena", posicao: "ATA", time: "Inter", liga: "Série A", temporada: "91", rating: 80, cost: 70 },

    // Inter 94
    { name: "W. Zenga", posicao: "GOL", time: "Inter", liga: "Série A", temporada: "94", rating: 83, cost: 80 },
    { name: "G. Bergomi", posicao: "ZAG", time: "Inter", liga: "Série A", temporada: "94", rating: 83, cost: 80 },
    { name: "R. Ferri", posicao: "ZAG", time: "Inter", liga: "Série A", temporada: "94", rating: 80, cost: 70 },
    { name: "M. Paganin", posicao: "ZAG", time: "Inter", liga: "Série A", temporada: "94", rating: 77, cost: 60 },
    { name: "A. Fontolan", posicao: "MEI", time: "Inter", liga: "Série A", temporada: "94", rating: 78, cost: 65 },
    { name: "W. Jonk", posicao: "MEI", time: "Inter", liga: "Série A", temporada: "94", rating: 81, cost: 75 },
    { name: "N. Berti", posicao: "MEI", time: "Inter", liga: "Série A", temporada: "94", rating: 80, cost: 70 },
    { name: "A. Manicone", posicao: "MEI", time: "Inter", liga: "Série A", temporada: "94", rating: 77, cost: 60 },
    { name: "A. Orlando", posicao: "MEI", time: "Inter", liga: "Série A", temporada: "94", rating: 77, cost: 60 },
    { name: "D. Bergkamp", posicao: "ATA", time: "Inter", liga: "Série A", temporada: "94", rating: 85, cost: 100 },
    { name: "R. Sosa", posicao: "ATA", time: "Inter", liga: "Série A", temporada: "94", rating: 81, cost: 75 },

    // Inter 98
    { name: "G. Pagliuca", posicao: "GOL", time: "Inter", liga: "Série A", temporada: "98", rating: 81, cost: 70 },
    { name: "G. Bergomi", posicao: "ZAG", time: "Inter", liga: "Série A", temporada: "98", rating: 81, cost: 75 },
    { name: "J. Zanetti", posicao: "ZAG", time: "Inter", liga: "Série A", temporada: "98", rating: 83, cost: 80 },
    { name: "T. West", posicao: "ZAG", time: "Inter", liga: "Série A", temporada: "98", rating: 80, cost: 70 },
    { name: "L. Sartor", posicao: "ZAG", time: "Inter", liga: "Série A", temporada: "98", rating: 77, cost: 60 },
    { name: "D. Simeone", posicao: "MEI", time: "Inter", liga: "Série A", temporada: "98", rating: 82, cost: 80 },
    { name: "A. Winter", posicao: "MEI", time: "Inter", liga: "Série A", temporada: "98", rating: 80, cost: 70 },
    { name: "Y. Djorkaeff", posicao: "MEI", time: "Inter", liga: "Série A", temporada: "98", rating: 84, cost: 90 },
    { name: "F. Moriero", posicao: "MEI", time: "Inter", liga: "Série A", temporada: "98", rating: 79, cost: 65 },
    { name: "Ronaldo", posicao: "ATA", time: "Inter", liga: "Série A", temporada: "98", rating: 93, cost: 170 },
    { name: "I. Zamorano", posicao: "ATA", time: "Inter", liga: "Série A", temporada: "98", rating: 83, cost: 85 },
    { name: "N. Kanu", posicao: "ATA", time: "Inter", liga: "Série A", temporada: "98", rating: 81, cost: 75 },

    // Parma 93
    { name: "M. Ballotta", posicao: "GOL", time: "Parma", liga: "Série A", temporada: "93", rating: 78, cost: 60 },
    { name: "L. Minotti", posicao: "ZAG", time: "Parma", liga: "Série A", temporada: "93", rating: 80, cost: 70 },
    { name: "L. Apolloni", posicao: "ZAG", time: "Parma", liga: "Série A", temporada: "93", rating: 80, cost: 70 },
    { name: "A. Benarrivo", posicao: "ZAG", time: "Parma", liga: "Série A", temporada: "93", rating: 81, cost: 75 },
    { name: "A. Di Chiara", posicao: "ZAG", time: "Parma", liga: "Série A", temporada: "93", rating: 79, cost: 65 },
    { name: "D. Zoratto", posicao: "MEI", time: "Parma", liga: "Série A", temporada: "93", rating: 78, cost: 60 },
    { name: "T. Brolin", posicao: "MEI", time: "Parma", liga: "Série A", temporada: "93", rating: 82, cost: 80 },
    { name: "G. Cuoghi", posicao: "MEI", time: "Parma", liga: "Série A", temporada: "93", rating: 77, cost: 55 },
    { name: "M. Osio", posicao: "MEI", time: "Parma", liga: "Série A", temporada: "93", rating: 77, cost: 55 },
    { name: "F. Asprilla", posicao: "ATA", time: "Parma", liga: "Série A", temporada: "93", rating: 83, cost: 85 },
    { name: "A. Melli", posicao: "ATA", time: "Parma", liga: "Série A", temporada: "93", rating: 79, cost: 65 },

    // Parma 95
    { name: "L. Bucci", posicao: "GOL", time: "Parma", liga: "Série A", temporada: "95", rating: 80, cost: 70 },
    { name: "L. Minotti", posicao: "ZAG", time: "Parma", liga: "Série A", temporada: "95", rating: 79, cost: 65 },
    { name: "F. Couto", posicao: "ZAG", time: "Parma", liga: "Série A", temporada: "95", rating: 82, cost: 80 },
    { name: "N. Sensini", posicao: "ZAG", time: "Parma", liga: "Série A", temporada: "95", rating: 82, cost: 80 },
    { name: "A. Benarrivo", posicao: "ZAG", time: "Parma", liga: "Série A", temporada: "95", rating: 80, cost: 70 },
    { name: "Dino Baggio", posicao: "MEI", time: "Parma", liga: "Série A", temporada: "95", rating: 82, cost: 80 },
    { name: "M. Crippa", posicao: "MEI", time: "Parma", liga: "Série A", temporada: "95", rating: 79, cost: 65 },
    { name: "G. Pin", posicao: "MEI", time: "Parma", liga: "Série A", temporada: "95", rating: 77, cost: 55 },
    { name: "G. Zola", posicao: "ATA", time: "Parma", liga: "Série A", temporada: "95", rating: 85, cost: 100 },
    { name: "F. Asprilla", posicao: "ATA", time: "Parma", liga: "Série A", temporada: "95", rating: 82, cost: 80 },
    { name: "H. Stoichkov", posicao: "ATA", time: "Parma", liga: "Série A", temporada: "95", rating: 86, cost: 110 },

    // Parma 99
    { name: "G. Buffon", posicao: "GOL", time: "Parma", liga: "Série A", temporada: "99", rating: 84, cost: 85 },
    { name: "M. Thuram", posicao: "ZAG", time: "Parma", liga: "Série A", temporada: "99", rating: 84, cost: 90 },
    { name: "F. Cannavaro", posicao: "ZAG", time: "Parma", liga: "Série A", temporada: "99", rating: 85, cost: 95 },
    { name: "N. Sensini", posicao: "ZAG", time: "Parma", liga: "Série A", temporada: "99", rating: 81, cost: 75 },
    { name: "A. Benarrivo", posicao: "ZAG", time: "Parma", liga: "Série A", temporada: "99", rating: 79, cost: 65 },
    { name: "J. S. Veron", posicao: "MEI", time: "Parma", liga: "Série A", temporada: "99", rating: 86, cost: 105 },
    { name: "A. Boghossian", posicao: "MEI", time: "Parma", liga: "Série A", temporada: "99", rating: 80, cost: 70 },
    { name: "D. Fuser", posicao: "MEI", time: "Parma", liga: "Série A", temporada: "99", rating: 79, cost: 60 },
    { name: "D. Baggio", posicao: "MEI", time: "Parma", liga: "Série A", temporada: "99", rating: 81, cost: 75 },
    { name: "H. Crespo", posicao: "ATA", time: "Parma", liga: "Série A", temporada: "99", rating: 85, cost: 100 },
    { name: "E. Chiesa", posicao: "ATA", time: "Parma", liga: "Série A", temporada: "99", rating: 81, cost: 70 },
    { name: "F. Asprilla", posicao: "ATA", time: "Parma", liga: "Série A", temporada: "99", rating: 80, cost: 70 },

    // Fiorentina 90
    { name: "A. Landucci", posicao: "GOL", time: "Fiorentina", liga: "Série A", temporada: "90", rating: 77, cost: 55 },
    { name: "G. Pin", posicao: "ZAG", time: "Fiorentina", liga: "Série A", temporada: "90", rating: 77, cost: 55 },
    { name: "S. Pioli", posicao: "ZAG", time: "Fiorentina", liga: "Série A", temporada: "90", rating: 78, cost: 60 },
    { name: "R. Volpecina", posicao: "ZAG", time: "Fiorentina", liga: "Série A", temporada: "90", rating: 77, cost: 55 },
    { name: "G. Battistini", posicao: "ZAG", time: "Fiorentina", liga: "Série A", temporada: "90", rating: 78, cost: 60 },
    { name: "Dunga", posicao: "MEI", time: "Fiorentina", liga: "Série A", temporada: "90", rating: 84, cost: 95 },
    { name: "R. Buso", posicao: "MEI", time: "Fiorentina", liga: "Série A", temporada: "90", rating: 78, cost: 60 },
    { name: "G. Iachini", posicao: "MEI", time: "Fiorentina", liga: "Série A", temporada: "90", rating: 77, cost: 55 },
    { name: "R. Baggio", posicao: "ATA", time: "Fiorentina", liga: "Série A", temporada: "90", rating: 90, cost: 140 },
    { name: "S. Borgonovo", posicao: "ATA", time: "Fiorentina", liga: "Série A", temporada: "90", rating: 79, cost: 65 },
    { name: "M. Nappi", posicao: "ATA", time: "Fiorentina", liga: "Série A", temporada: "90", rating: 77, cost: 55 },

    // Fiorentina 96
    { name: "F. Toldo", posicao: "GOL", time: "Fiorentina", liga: "Série A", temporada: "96", rating: 80, cost: 65 },
    { name: "P. Padalino", posicao: "ZAG", time: "Fiorentina", liga: "Série A", temporada: "96", rating: 79, cost: 65 },
    { name: "L. Amoruso", posicao: "ZAG", time: "Fiorentina", liga: "Série A", temporada: "96", rating: 79, cost: 65 },
    { name: "A. Sottil", posicao: "ZAG", time: "Fiorentina", liga: "Série A", temporada: "96", rating: 78, cost: 60 },
    { name: "D. Carnasciali", posicao: "ZAG", time: "Fiorentina", liga: "Série A", temporada: "96", rating: 78, cost: 60 },
    { name: "Rui Costa", posicao: "MEI", time: "Fiorentina", liga: "Série A", temporada: "96", rating: 86, cost: 100 },
    { name: "S. Schwarz", posicao: "MEI", time: "Fiorentina", liga: "Série A", temporada: "96", rating: 81, cost: 75 },
    { name: "S. Cois", posicao: "MEI", time: "Fiorentina", liga: "Série A", temporada: "96", rating: 78, cost: 60 },
    { name: "E. Bigica", posicao: "MEI", time: "Fiorentina", liga: "Série A", temporada: "96", rating: 77, cost: 55 },
    { name: "G. Batistuta", posicao: "ATA", time: "Fiorentina", liga: "Série A", temporada: "96", rating: 89, cost: 130 },
    { name: "F. Baiano", posicao: "ATA", time: "Fiorentina", liga: "Série A", temporada: "96", rating: 79, cost: 65 },

    // Fiorentina 98
    { name: "F. Toldo", posicao: "GOL", time: "Fiorentina", liga: "Série A", temporada: "98", rating: 81, cost: 70 },
    { name: "T. Repka", posicao: "ZAG", time: "Fiorentina", liga: "Série A", temporada: "98", rating: 79, cost: 65 },
    { name: "P. Padalino", posicao: "ZAG", time: "Fiorentina", liga: "Série A", temporada: "98", rating: 79, cost: 65 },
    { name: "J. Heinrich", posicao: "ZAG", time: "Fiorentina", liga: "Série A", temporada: "98", rating: 78, cost: 60 },
    { name: "G. Falcone", posicao: "ZAG", time: "Fiorentina", liga: "Série A", temporada: "98", rating: 78, cost: 60 },
    { name: "Rui Costa", posicao: "MEI", time: "Fiorentina", liga: "Série A", temporada: "98", rating: 86, cost: 100 },
    { name: "S. Cois", posicao: "MEI", time: "Fiorentina", liga: "Série A", temporada: "98", rating: 78, cost: 60 },
    { name: "L. Amoruso", posicao: "MEI", time: "Fiorentina", liga: "Série A", temporada: "98", rating: 79, cost: 65 },
    { name: "A. Robbiati", posicao: "MEI", time: "Fiorentina", liga: "Série A", temporada: "98", rating: 78, cost: 60 },
    { name: "G. Batistuta", posicao: "ATA", time: "Fiorentina", liga: "Série A", temporada: "98", rating: 89, cost: 130 },
    { name: "Edmundo", posicao: "ATA", time: "Fiorentina", liga: "Série A", temporada: "98", rating: 84, cost: 95 },
    { name: "L. Oliveira", posicao: "ATA", time: "Fiorentina", liga: "Série A", temporada: "98", rating: 80, cost: 70 },

    // Roma 91
    { name: "G. Zinetti", posicao: "GOL", time: "Roma", liga: "Série A", temporada: "91", rating: 77, cost: 55 },
    { name: "Aldair", posicao: "ZAG", time: "Roma", liga: "Série A", temporada: "91", rating: 84, cost: 90 },
    { name: "S. Nela", posicao: "ZAG", time: "Roma", liga: "Série A", temporada: "91", rating: 80, cost: 70 },
    { name: "G. Tempestilli", posicao: "ZAG", time: "Roma", liga: "Série A", temporada: "91", rating: 78, cost: 60 },
    { name: "T. Berthold", posicao: "ZAG", time: "Roma", liga: "Série A", temporada: "91", rating: 81, cost: 75 },
    { name: "G. Giannini", posicao: "MEI", time: "Roma", liga: "Série A", temporada: "91", rating: 83, cost: 85 },
    { name: "F. Desideri", posicao: "MEI", time: "Roma", liga: "Série A", temporada: "91", rating: 79, cost: 65 },
    { name: "G. Piacentini", posicao: "MEI", time: "Roma", liga: "Série A", temporada: "91", rating: 77, cost: 55 },
    { name: "R. Di Mauro", posicao: "MEI", time: "Roma", liga: "Série A", temporada: "91", rating: 78, cost: 60 },
    { name: "R. Voller", posicao: "ATA", time: "Roma", liga: "Série A", temporada: "91", rating: 84, cost: 95 },
    { name: "R. Rizzitelli", posicao: "ATA", time: "Roma", liga: "Série A", temporada: "91", rating: 79, cost: 65 },

    // Roma 96
    { name: "G. Cervone", posicao: "GOL", time: "Roma", liga: "Série A", temporada: "96", rating: 79, cost: 65 },
    { name: "Aldair", posicao: "ZAG", time: "Roma", liga: "Série A", temporada: "96", rating: 84, cost: 90 },
    { name: "S. Lanna", posicao: "ZAG", time: "Roma", liga: "Série A", temporada: "96", rating: 77, cost: 55 },
    { name: "F. Petruzzi", posicao: "ZAG", time: "Roma", liga: "Série A", temporada: "96", rating: 78, cost: 60 },
    { name: "A. Carboni", posicao: "ZAG", time: "Roma", liga: "Série A", temporada: "96", rating: 79, cost: 65 },
    { name: "G. Giannini", posicao: "MEI", time: "Roma", liga: "Série A", temporada: "96", rating: 81, cost: 75 },
    { name: "D. Tommasi", posicao: "MEI", time: "Roma", liga: "Série A", temporada: "96", rating: 80, cost: 70 },
    { name: "L. Di Biagio", posicao: "MEI", time: "Roma", liga: "Série A", temporada: "96", rating: 81, cost: 75 },
    { name: "F. Moriero", posicao: "MEI", time: "Roma", liga: "Série A", temporada: "96", rating: 79, cost: 65 },
    { name: "A. Balbo", posicao: "ATA", time: "Roma", liga: "Série A", temporada: "96", rating: 83, cost: 85 },
    { name: "D. Fonseca", posicao: "ATA", time: "Roma", liga: "Série A", temporada: "96", rating: 81, cost: 75 },

    // Roma 00
    { name: "F. Antonioli", posicao: "GOL", time: "Roma", liga: "Série A", temporada: "00", rating: 80, cost: 70 },
    { name: "W. Samuel", posicao: "ZAG", time: "Roma", liga: "Série A", temporada: "00", rating: 84, cost: 90 },
    { name: "A. C. Zago", posicao: "ZAG", time: "Roma", liga: "Série A", temporada: "00", rating: 80, cost: 70 },
    { name: "Aldair", posicao: "ZAG", time: "Roma", liga: "Série A", temporada: "00", rating: 82, cost: 80 },
    { name: "Cafu", posicao: "ZAG", time: "Roma", liga: "Série A", temporada: "00", rating: 85, cost: 100 },
    { name: "D. Tommasi", posicao: "MEI", time: "Roma", liga: "Série A", temporada: "00", rating: 81, cost: 75 },
    { name: "Emerson", posicao: "MEI", time: "Roma", liga: "Série A", temporada: "00", rating: 83, cost: 85 },
    { name: "C. Zanetti", posicao: "MEI", time: "Roma", liga: "Série A", temporada: "00", rating: 79, cost: 65 },
    { name: "F. Totti", posicao: "ATA", time: "Roma", liga: "Série A", temporada: "00", rating: 87, cost: 110 },
    { name: "G. Batistuta", posicao: "ATA", time: "Roma", liga: "Série A", temporada: "00", rating: 89, cost: 130 },
    { name: "V. Montella", posicao: "ATA", time: "Roma", liga: "Série A", temporada: "00", rating: 83, cost: 85 },
    { name: "M. Delvecchio", posicao: "ATA", time: "Roma", liga: "Série A", temporada: "00", rating: 80, cost: 70 },

    // Lazio 93
    { name: "F. Orsi", posicao: "GOL", time: "Lazio", liga: "Série A", temporada: "93", rating: 78, cost: 60 },
    { name: "A. Luzardi", posicao: "ZAG", time: "Lazio", liga: "Série A", temporada: "93", rating: 77, cost: 55 },
    { name: "L. Corino", posicao: "ZAG", time: "Lazio", liga: "Série A", temporada: "93", rating: 77, cost: 55 },
    { name: "G. Favalli", posicao: "ZAG", time: "Lazio", liga: "Série A", temporada: "93", rating: 79, cost: 65 },
    { name: "C. Bonomi", posicao: "ZAG", time: "Lazio", liga: "Série A", temporada: "93", rating: 77, cost: 55 },
    { name: "A. Winter", posicao: "MEI", time: "Lazio", liga: "Série A", temporada: "93", rating: 81, cost: 75 },
    { name: "P. Gascoigne", posicao: "MEI", time: "Lazio", liga: "Série A", temporada: "93", rating: 83, cost: 85 },
    { name: "D. Fuser", posicao: "MEI", time: "Lazio", liga: "Série A", temporada: "93", rating: 79, cost: 60 },
    { name: "T. Doll", posicao: "MEI", time: "Lazio", liga: "Série A", temporada: "93", rating: 80, cost: 70 },
    { name: "G. Signori", posicao: "ATA", time: "Lazio", liga: "Série A", temporada: "93", rating: 84, cost: 95 },
    { name: "K. Riedle", posicao: "ATA", time: "Lazio", liga: "Série A", temporada: "93", rating: 82, cost: 80 },

    // Lazio 98
    { name: "L. Marchegiani", posicao: "GOL", time: "Lazio", liga: "Série A", temporada: "98", rating: 81, cost: 70 },
    { name: "A. Nesta", posicao: "ZAG", time: "Lazio", liga: "Série A", temporada: "98", rating: 86, cost: 105 },
    { name: "P. Negro", posicao: "ZAG", time: "Lazio", liga: "Série A", temporada: "98", rating: 79, cost: 65 },
    { name: "G. Favalli", posicao: "ZAG", time: "Lazio", liga: "Série A", temporada: "98", rating: 80, cost: 70 },
    { name: "M. Pancaro", posicao: "ZAG", time: "Lazio", liga: "Série A", temporada: "98", rating: 78, cost: 60 },
    { name: "P. Nedved", posicao: "MEI", time: "Lazio", liga: "Série A", temporada: "98", rating: 85, cost: 100 },
    { name: "M. Almeyda", posicao: "MEI", time: "Lazio", liga: "Série A", temporada: "98", rating: 81, cost: 75 },
    { name: "V. Jugovic", posicao: "MEI", time: "Lazio", liga: "Série A", temporada: "98", rating: 82, cost: 80 },
    { name: "D. Fuser", posicao: "MEI", time: "Lazio", liga: "Série A", temporada: "98", rating: 80, cost: 70 },
    { name: "R. Mancini", posicao: "ATA", time: "Lazio", liga: "Série A", temporada: "98", rating: 84, cost: 95 },
    { name: "P. Casiraghi", posicao: "ATA", time: "Lazio", liga: "Série A", temporada: "98", rating: 81, cost: 75 },

    // Lazio 00
    { name: "L. Marchegiani", posicao: "GOL", time: "Lazio", liga: "Série A", temporada: "00", rating: 80, cost: 65 },
    { name: "A. Nesta", posicao: "ZAG", time: "Lazio", liga: "Série A", temporada: "00", rating: 86, cost: 105 },
    { name: "S. Mihajlovic", posicao: "ZAG", time: "Lazio", liga: "Série A", temporada: "00", rating: 83, cost: 85 },
    { name: "M. Pancaro", posicao: "ZAG", time: "Lazio", liga: "Série A", temporada: "00", rating: 79, cost: 65 },
    { name: "P. Negro", posicao: "ZAG", time: "Lazio", liga: "Série A", temporada: "00", rating: 79, cost: 65 },
    { name: "J. S. Veron", posicao: "MEI", time: "Lazio", liga: "Série A", temporada: "00", rating: 86, cost: 105 },
    { name: "D. Simeone", posicao: "MEI", time: "Lazio", liga: "Série A", temporada: "00", rating: 82, cost: 80 },
    { name: "P. Nedved", posicao: "MEI", time: "Lazio", liga: "Série A", temporada: "00", rating: 86, cost: 105 },
    { name: "S. Conceicao", posicao: "MEI", time: "Lazio", liga: "Série A", temporada: "00", rating: 81, cost: 75 },
    { name: "M. Salas", posicao: "ATA", time: "Lazio", liga: "Série A", temporada: "00", rating: 84, cost: 95 },
    { name: "S. Inzaghi", posicao: "ATA", time: "Lazio", liga: "Série A", temporada: "00", rating: 80, cost: 70 },
    { name: "A. Boksic", posicao: "ATA", time: "Lazio", liga: "Série A", temporada: "00", rating: 81, cost: 75 },

    // Napoli 90
    { name: "G. Galli", posicao: "GOL", time: "Napoli", liga: "Série A", temporada: "90", rating: 80, cost: 65 },
    { name: "C. Ferrara", posicao: "ZAG", time: "Napoli", liga: "Série A", temporada: "90", rating: 83, cost: 80 },
    { name: "G. Francini", posicao: "ZAG", time: "Napoli", liga: "Série A", temporada: "90", rating: 78, cost: 60 },
    { name: "G. Corradini", posicao: "ZAG", time: "Napoli", liga: "Série A", temporada: "90", rating: 78, cost: 60 },
    { name: "M. Baroni", posicao: "ZAG", time: "Napoli", liga: "Série A", temporada: "90", rating: 78, cost: 60 },
    { name: "F. De Napoli", posicao: "MEI", time: "Napoli", liga: "Série A", temporada: "90", rating: 80, cost: 70 },
    { name: "Alemao", posicao: "MEI", time: "Napoli", liga: "Série A", temporada: "90", rating: 82, cost: 80 },
    { name: "M. Crippa", posicao: "MEI", time: "Napoli", liga: "Série A", temporada: "90", rating: 78, cost: 60 },
    { name: "Maradona", posicao: "MEI", time: "Napoli", liga: "Série A", temporada: "90", rating: 93, cost: 170 },
    { name: "Careca", posicao: "ATA", time: "Napoli", liga: "Série A", temporada: "90", rating: 86, cost: 105 },
    { name: "A. Carnevale", posicao: "ATA", time: "Napoli", liga: "Série A", temporada: "90", rating: 79, cost: 65 },

    // Napoli 93
    { name: "G. Galli", posicao: "GOL", time: "Napoli", liga: "Série A", temporada: "93", rating: 78, cost: 60 },
    { name: "C. Ferrara", posicao: "ZAG", time: "Napoli", liga: "Série A", temporada: "93", rating: 82, cost: 75 },
    { name: "M. Tarantino", posicao: "ZAG", time: "Napoli", liga: "Série A", temporada: "93", rating: 77, cost: 55 },
    { name: "F. Policano", posicao: "ZAG", time: "Napoli", liga: "Série A", temporada: "93", rating: 78, cost: 60 },
    { name: "G. Corradini", posicao: "ZAG", time: "Napoli", liga: "Série A", temporada: "93", rating: 77, cost: 55 },
    { name: "F. Pari", posicao: "MEI", time: "Napoli", liga: "Série A", temporada: "93", rating: 78, cost: 60 },
    { name: "J. Thern", posicao: "MEI", time: "Napoli", liga: "Série A", temporada: "93", rating: 80, cost: 70 },
    { name: "D. Mauro", posicao: "MEI", time: "Napoli", liga: "Série A", temporada: "93", rating: 77, cost: 55 },
    { name: "G. Zola", posicao: "ATA", time: "Napoli", liga: "Série A", temporada: "93", rating: 83, cost: 85 },
    { name: "D. Fonseca", posicao: "ATA", time: "Napoli", liga: "Série A", temporada: "93", rating: 81, cost: 75 },
    { name: "Careca", posicao: "ATA", time: "Napoli", liga: "Série A", temporada: "93", rating: 82, cost: 80 },

    // Napoli 97
    { name: "P. Taglialatela", posicao: "GOL", time: "Napoli", liga: "Série A", temporada: "97", rating: 79, cost: 65 },
    { name: "R. Ayala", posicao: "ZAG", time: "Napoli", liga: "Série A", temporada: "97", rating: 80, cost: 70 },
    { name: "M. Milanese", posicao: "ZAG", time: "Napoli", liga: "Série A", temporada: "97", rating: 77, cost: 55 },
    { name: "F. Baldini", posicao: "ZAG", time: "Napoli", liga: "Série A", temporada: "97", rating: 77, cost: 55 },
    { name: "F. Turrini", posicao: "MEI", time: "Napoli", liga: "Série A", temporada: "97", rating: 78, cost: 60 },
    { name: "A. Boghossian", posicao: "MEI", time: "Napoli", liga: "Série A", temporada: "97", rating: 79, cost: 65 },
    { name: "F. Pecchia", posicao: "MEI", time: "Napoli", liga: "Série A", temporada: "97", rating: 78, cost: 60 },
    { name: "G. Goretti", posicao: "MEI", time: "Napoli", liga: "Série A", temporada: "97", rating: 76, cost: 50 },
    { name: "N. Caccia", posicao: "ATA", time: "Napoli", liga: "Série A", temporada: "97", rating: 77, cost: 55 },
    { name: "C. Aglietti", posicao: "ATA", time: "Napoli", liga: "Série A", temporada: "97", rating: 77, cost: 55 },
    { name: "I. Protti", posicao: "ATA", time: "Napoli", liga: "Série A", temporada: "97", rating: 78, cost: 60 },

    // Sampdoria 91
    { name: "G. Pagliuca", posicao: "GOL", time: "Sampdoria", liga: "Série A", temporada: "91", rating: 84, cost: 85 },
    { name: "P. Vierchowod", posicao: "ZAG", time: "Sampdoria", liga: "Série A", temporada: "91", rating: 83, cost: 80 },
    { name: "M. Mannini", posicao: "ZAG", time: "Sampdoria", liga: "Série A", temporada: "91", rating: 79, cost: 65 },
    { name: "M. Lanna", posicao: "ZAG", time: "Sampdoria", liga: "Série A", temporada: "91", rating: 78, cost: 60 },
    { name: "S. Katanec", posicao: "ZAG", time: "Sampdoria", liga: "Série A", temporada: "91", rating: 80, cost: 70 },
    { name: "A. Lombardo", posicao: "MEI", time: "Sampdoria", liga: "Série A", temporada: "91", rating: 82, cost: 80 },
    { name: "T. Cerezo", posicao: "MEI", time: "Sampdoria", liga: "Série A", temporada: "91", rating: 81, cost: 75 },
    { name: "F. Pari", posicao: "MEI", time: "Sampdoria", liga: "Série A", temporada: "91", rating: 78, cost: 60 },
    { name: "G. Dossena", posicao: "MEI", time: "Sampdoria", liga: "Série A", temporada: "91", rating: 80, cost: 70 },
    { name: "R. Mancini", posicao: "ATA", time: "Sampdoria", liga: "Série A", temporada: "91", rating: 84, cost: 95 },
    { name: "G. Vialli", posicao: "ATA", time: "Sampdoria", liga: "Série A", temporada: "91", rating: 85, cost: 100 },

    // Sampdoria 94
    { name: "G. Pagliuca", posicao: "GOL", time: "Sampdoria", liga: "Série A", temporada: "94", rating: 83, cost: 80 },
    { name: "P. Vierchowod", posicao: "ZAG", time: "Sampdoria", liga: "Série A", temporada: "94", rating: 82, cost: 75 },
    { name: "M. Rossi", posicao: "ZAG", time: "Sampdoria", liga: "Série A", temporada: "94", rating: 77, cost: 55 },
    { name: "G. Sacchetti", posicao: "ZAG", time: "Sampdoria", liga: "Série A", temporada: "94", rating: 77, cost: 55 },
    { name: "M. Serena", posicao: "ZAG", time: "Sampdoria", liga: "Série A", temporada: "94", rating: 78, cost: 60 },
    { name: "R. Gullit", posicao: "MEI", time: "Sampdoria", liga: "Série A", temporada: "94", rating: 87, cost: 120 },
    { name: "D. Platt", posicao: "MEI", time: "Sampdoria", liga: "Série A", temporada: "94", rating: 82, cost: 80 },
    { name: "V. Jugovic", posicao: "MEI", time: "Sampdoria", liga: "Série A", temporada: "94", rating: 81, cost: 75 },
    { name: "A. Evani", posicao: "MEI", time: "Sampdoria", liga: "Série A", temporada: "94", rating: 79, cost: 65 },
    { name: "R. Mancini", posicao: "ATA", time: "Sampdoria", liga: "Série A", temporada: "94", rating: 83, cost: 90 },
    { name: "A. Lombardo", posicao: "ATA", time: "Sampdoria", liga: "Série A", temporada: "94", rating: 81, cost: 75 },

    // Sampdoria 97
    { name: "F. Ferron", posicao: "GOL", time: "Sampdoria", liga: "Série A", temporada: "97", rating: 79, cost: 60 },
    { name: "S. Mihajlovic", posicao: "ZAG", time: "Sampdoria", liga: "Série A", temporada: "97", rating: 81, cost: 75 },
    { name: "M. Mannini", posicao: "ZAG", time: "Sampdoria", liga: "Série A", temporada: "97", rating: 78, cost: 60 },
    { name: "V. Pesaresi", posicao: "ZAG", time: "Sampdoria", liga: "Série A", temporada: "97", rating: 76, cost: 50 },
    { name: "M. Franceschetti", posicao: "ZAG", time: "Sampdoria", liga: "Série A", temporada: "97", rating: 76, cost: 50 },
    { name: "J. S. Veron", posicao: "MEI", time: "Sampdoria", liga: "Série A", temporada: "97", rating: 83, cost: 85 },
    { name: "C. Karembeu", posicao: "MEI", time: "Sampdoria", liga: "Série A", temporada: "97", rating: 81, cost: 75 },
    { name: "P. Laigle", posicao: "MEI", time: "Sampdoria", liga: "Série A", temporada: "97", rating: 77, cost: 55 },
    { name: "G. Iacopino", posicao: "MEI", time: "Sampdoria", liga: "Série A", temporada: "97", rating: 75, cost: 45 },
    { name: "R. Mancini", posicao: "ATA", time: "Sampdoria", liga: "Série A", temporada: "97", rating: 82, cost: 80 },
    { name: "V. Montella", posicao: "ATA", time: "Sampdoria", liga: "Série A", temporada: "97", rating: 81, cost: 75 },

    // Torino 92
    { name: "L. Marchegiani", posicao: "GOL", time: "Torino", liga: "Série A", temporada: "92", rating: 81, cost: 70 },
    { name: "G. Annoni", posicao: "ZAG", time: "Torino", liga: "Série A", temporada: "92", rating: 78, cost: 60 },
    { name: "R. Cravero", posicao: "ZAG", time: "Torino", liga: "Série A", temporada: "92", rating: 79, cost: 65 },
    { name: "F. Policano", posicao: "ZAG", time: "Torino", liga: "Série A", temporada: "92", rating: 78, cost: 60 },
    { name: "P. Bruno", posicao: "ZAG", time: "Torino", liga: "Série A", temporada: "92", rating: 77, cost: 55 },
    { name: "G. Lentini", posicao: "MEI", time: "Torino", liga: "Série A", temporada: "92", rating: 83, cost: 85 },
    { name: "E. Scifo", posicao: "MEI", time: "Torino", liga: "Série A", temporada: "92", rating: 82, cost: 80 },
    { name: "R. Martin Vazquez", posicao: "MEI", time: "Torino", liga: "Série A", temporada: "92", rating: 81, cost: 75 },
    { name: "G. Venturin", posicao: "MEI", time: "Torino", liga: "Série A", temporada: "92", rating: 77, cost: 55 },
    { name: "W. Casagrande", posicao: "ATA", time: "Torino", liga: "Série A", temporada: "92", rating: 81, cost: 75 },
    { name: "G. Bresciani", posicao: "ATA", time: "Torino", liga: "Série A", temporada: "92", rating: 77, cost: 55 },

    // Atalanta 96
    { name: "F. Ferron", posicao: "GOL", time: "Atalanta", liga: "Série A", temporada: "96", rating: 79, cost: 60 },
    { name: "P. Montero", posicao: "ZAG", time: "Atalanta", liga: "Série A", temporada: "96", rating: 82, cost: 75 },
    { name: "Y. Herrera", posicao: "ZAG", time: "Atalanta", liga: "Série A", temporada: "96", rating: 76, cost: 50 },
    { name: "S. Boselli", posicao: "ZAG", time: "Atalanta", liga: "Série A", temporada: "96", rating: 75, cost: 45 },
    { name: "M. Valentini", posicao: "ZAG", time: "Atalanta", liga: "Série A", temporada: "96", rating: 75, cost: 45 },
    { name: "D. Fortunato", posicao: "MEI", time: "Atalanta", liga: "Série A", temporada: "96", rating: 77, cost: 55 },
    { name: "D. Morfeo", posicao: "MEI", time: "Atalanta", liga: "Série A", temporada: "96", rating: 80, cost: 70 },
    { name: "M. Sgrò", posicao: "MEI", time: "Atalanta", liga: "Série A", temporada: "96", rating: 77, cost: 55 },
    { name: "F. Gallo", posicao: "MEI", time: "Atalanta", liga: "Série A", temporada: "96", rating: 76, cost: 50 },
    { name: "P. Inzaghi", posicao: "ATA", time: "Atalanta", liga: "Série A", temporada: "96", rating: 83, cost: 85 },
    { name: "C. Vieri", posicao: "ATA", time: "Atalanta", liga: "Série A", temporada: "96", rating: 82, cost: 80 },

    // Brescia 00
    { name: "P. Srnicek", posicao: "GOL", time: "Brescia", liga: "Série A", temporada: "00", rating: 77, cost: 55 },
    { name: "A. Calori", posicao: "ZAG", time: "Brescia", liga: "Série A", temporada: "00", rating: 78, cost: 60 },
    { name: "F. Petruzzi", posicao: "ZAG", time: "Brescia", liga: "Série A", temporada: "00", rating: 77, cost: 55 },
    { name: "D. Bonera", posicao: "ZAG", time: "Brescia", liga: "Série A", temporada: "00", rating: 78, cost: 60 },
    { name: "A. Diana", posicao: "ZAG", time: "Brescia", liga: "Série A", temporada: "00", rating: 77, cost: 55 },
    { name: "A. Pirlo", posicao: "MEI", time: "Brescia", liga: "Série A", temporada: "00", rating: 83, cost: 85 },
    { name: "P. Guardiola", posicao: "MEI", time: "Brescia", liga: "Série A", temporada: "00", rating: 83, cost: 85 },
    { name: "A. Filippini", posicao: "MEI", time: "Brescia", liga: "Série A", temporada: "00", rating: 77, cost: 55 },
    { name: "S. Bachini", posicao: "MEI", time: "Brescia", liga: "Série A", temporada: "00", rating: 76, cost: 50 },
    { name: "R. Baggio", posicao: "ATA", time: "Brescia", liga: "Série A", temporada: "00", rating: 90, cost: 140 },
    { name: "D. Hubner", posicao: "ATA", time: "Brescia", liga: "Série A", temporada: "00", rating: 81, cost: 75 },

    // Cagliari 93
    { name: "V. Fiori", posicao: "GOL", time: "Cagliari", liga: "Série A", temporada: "93", rating: 78, cost: 60 },
    { name: "A. Napoli", posicao: "ZAG", time: "Cagliari", liga: "Série A", temporada: "93", rating: 76, cost: 50 },
    { name: "V. Firicano", posicao: "ZAG", time: "Cagliari", liga: "Série A", temporada: "93", rating: 77, cost: 55 },
    { name: "V. Pusceddu", posicao: "ZAG", time: "Cagliari", liga: "Série A", temporada: "93", rating: 77, cost: 55 },
    { name: "G. Festa", posicao: "ZAG", time: "Cagliari", liga: "Série A", temporada: "93", rating: 77, cost: 55 },
    { name: "G. Matteoli", posicao: "MEI", time: "Cagliari", liga: "Série A", temporada: "93", rating: 79, cost: 65 },
    { name: "J. Herrera", posicao: "MEI", time: "Cagliari", liga: "Série A", temporada: "93", rating: 78, cost: 60 },
    { name: "L. Oliveira", posicao: "MEI", time: "Cagliari", liga: "Série A", temporada: "93", rating: 79, cost: 65 },
    { name: "M. Sanna", posicao: "MEI", time: "Cagliari", liga: "Série A", temporada: "93", rating: 76, cost: 50 },
    { name: "E. Francescoli", posicao: "ATA", time: "Cagliari", liga: "Série A", temporada: "93", rating: 84, cost: 95 },
    { name: "J. Dely Valdes", posicao: "ATA", time: "Cagliari", liga: "Série A", temporada: "93", rating: 80, cost: 70 },

    // Foggia 92
    { name: "F. Mancini", posicao: "GOL", time: "Foggia", liga: "Série A", temporada: "92", rating: 78, cost: 60 },
    { name: "S. Matrecano", posicao: "ZAG", time: "Foggia", liga: "Série A", temporada: "92", rating: 76, cost: 50 },
    { name: "A. Consagra", posicao: "ZAG", time: "Foggia", liga: "Série A", temporada: "92", rating: 75, cost: 45 },
    { name: "A. Codispoti", posicao: "ZAG", time: "Foggia", liga: "Série A", temporada: "92", rating: 75, cost: 45 },
    { name: "F. Piccioni", posicao: "ZAG", time: "Foggia", liga: "Série A", temporada: "92", rating: 76, cost: 50 },
    { name: "I. Shalimov", posicao: "MEI", time: "Foggia", liga: "Série A", temporada: "92", rating: 81, cost: 75 },
    { name: "L. Di Biagio", posicao: "MEI", time: "Foggia", liga: "Série A", temporada: "92", rating: 78, cost: 60 },
    { name: "F. Senso", posicao: "MEI", time: "Foggia", liga: "Série A", temporada: "92", rating: 75, cost: 45 },
    { name: "G. Signori", posicao: "ATA", time: "Foggia", liga: "Série A", temporada: "92", rating: 82, cost: 85 },
    { name: "F. Baiano", posicao: "ATA", time: "Foggia", liga: "Série A", temporada: "92", rating: 79, cost: 65 },
    { name: "R. Rambaudi", posicao: "ATA", time: "Foggia", liga: "Série A", temporada: "92", rating: 78, cost: 60 },

    // Ascoli 91
    { name: "F. Lorieri", posicao: "GOL", time: "Ascoli", liga: "Série A", temporada: "91", rating: 77, cost: 55 },
    { name: "A. Aloisi", posicao: "ZAG", time: "Ascoli", liga: "Série A", temporada: "91", rating: 75, cost: 45 },
    { name: "P. Marcato", posicao: "ZAG", time: "Ascoli", liga: "Série A", temporada: "91", rating: 74, cost: 40 },
    { name: "C. Benetti", posicao: "ZAG", time: "Ascoli", liga: "Série A", temporada: "91", rating: 75, cost: 45 },
    { name: "F. Destro", posicao: "ZAG", time: "Ascoli", liga: "Série A", temporada: "91", rating: 75, cost: 45 },
    { name: "P. Troglio", posicao: "MEI", time: "Ascoli", liga: "Série A", temporada: "91", rating: 78, cost: 60 },
    { name: "G. Cavaliere", posicao: "MEI", time: "Ascoli", liga: "Série A", temporada: "91", rating: 74, cost: 40 },
    { name: "A. Carbone", posicao: "MEI", time: "Ascoli", liga: "Série A", temporada: "91", rating: 76, cost: 50 },
    { name: "B. Cvetkovic", posicao: "MEI", time: "Ascoli", liga: "Série A", temporada: "91", rating: 76, cost: 50 },
    { name: "O. Bierhoff", posicao: "ATA", time: "Ascoli", liga: "Série A", temporada: "91", rating: 79, cost: 65 },
    { name: "W. Casagrande", posicao: "ATA", time: "Ascoli", liga: "Série A", temporada: "91", rating: 79, cost: 65 },

    // Empoli 98
    { name: "A. Pagotto", posicao: "GOL", time: "Empoli", liga: "Série A", temporada: "98", rating: 76, cost: 50 },
    { name: "F. Baldini", posicao: "ZAG", time: "Empoli", liga: "Série A", temporada: "98", rating: 76, cost: 50 },
    { name: "S. Bianconi", posicao: "ZAG", time: "Empoli", liga: "Série A", temporada: "98", rating: 75, cost: 45 },
    { name: "G. Fusco", posicao: "ZAG", time: "Empoli", liga: "Série A", temporada: "98", rating: 74, cost: 40 },
    { name: "G. Lucenti", posicao: "ZAG", time: "Empoli", liga: "Série A", temporada: "98", rating: 75, cost: 45 },
    { name: "F. Ficini", posicao: "MEI", time: "Empoli", liga: "Série A", temporada: "98", rating: 75, cost: 45 },
    { name: "G. Martusciello", posicao: "MEI", time: "Empoli", liga: "Série A", temporada: "98", rating: 77, cost: 55 },
    { name: "S. Pane", posicao: "MEI", time: "Empoli", liga: "Série A", temporada: "98", rating: 74, cost: 40 },
    { name: "M. Cappellini", posicao: "MEI", time: "Empoli", liga: "Série A", temporada: "98", rating: 75, cost: 45 },
    { name: "A. Di Natale", posicao: "ATA", time: "Empoli", liga: "Série A", temporada: "98", rating: 80, cost: 75 },
    { name: "C. Esposito", posicao: "ATA", time: "Empoli", liga: "Série A", temporada: "98", rating: 75, cost: 45 },

    // Genoa 91
    { name: "S. Braglia", posicao: "GOL", time: "Genoa", liga: "Série A", temporada: "91", rating: 78, cost: 60 },
    { name: "Branco", posicao: "ZAG", time: "Genoa", liga: "Série A", temporada: "91", rating: 82, cost: 80 },
    { name: "G. Signorini", posicao: "ZAG", time: "Genoa", liga: "Série A", temporada: "91", rating: 79, cost: 65 },
    { name: "V. Torrente", posicao: "ZAG", time: "Genoa", liga: "Série A", temporada: "91", rating: 78, cost: 60 },
    { name: "N. Caricola", posicao: "ZAG", time: "Genoa", liga: "Série A", temporada: "91", rating: 77, cost: 55 },
    { name: "G. Ruotolo", posicao: "MEI", time: "Genoa", liga: "Série A", temporada: "91", rating: 78, cost: 60 },
    { name: "S. Eranio", posicao: "MEI", time: "Genoa", liga: "Série A", temporada: "91", rating: 80, cost: 70 },
    { name: "M. Bortolazzi", posicao: "MEI", time: "Genoa", liga: "Série A", temporada: "91", rating: 77, cost: 55 },
    { name: "F. Onorati", posicao: "MEI", time: "Genoa", liga: "Série A", temporada: "91", rating: 77, cost: 55 },
    { name: "C. Aguilera", posicao: "ATA", time: "Genoa", liga: "Série A", temporada: "91", rating: 81, cost: 75 },
    { name: "T. Skuhravy", posicao: "ATA", time: "Genoa", liga: "Série A", temporada: "91", rating: 82, cost: 80 }
    // QUANDO SUBIR OUTRAS LIGAS, BASTA ADICIONAR ABAIXO:
    // { name: "David Beckham", posicao: "MEI", time: "Man. United", liga: "Premier League", temporada: "99", rating: 88, cost: 120 }
];